# Generated by Django 3.2.7 on 2021-09-24 11:29

from django.db import migrations
import issuetracking.models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracking', '0002_comment_contributor_issue_project'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', issuetracking.models.UserManager()),
            ],
        ),
    ]
