# Generated by Django 3.2.7 on 2021-09-24 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracking', '0003_alter_user_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.ManyToManyField(through='issuetracking.Contributor', to=settings.AUTH_USER_MODEL),
        ),
    ]
