# Generated by Django 3.2.7 on 2021-09-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracking', '0004_project_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='members',
        ),
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('F', 'FAIBLE'), ('M', 'MOYENNE'), ('E', 'ELEVEE')], max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('AF', 'à faire'), ('EC', 'en cours'), ('T', 'terminé')], max_length=255),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('BUG', 'BUG'), ('AMELIORATION', 'AMELIORATION'), ('TACHE', 'TACHE')], max_length=255),
        ),
    ]
