# Generated by Django 3.2.7 on 2021-09-28 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issuetracking', '0005_auto_20210927_0926'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='contributor',
            unique_together={('project', 'user')},
        ),
    ]
